### ISSUE TITLE
Adding new emotion sliders

### ISSUE THREAD

**Issue by LeilaIliffeHodgetts** [LilyFG/wheels-of-fortune#2]
In the index.html I've copied the slider_sad code and edited it to say 'relieved'. I've also added 'slider_relieved' to the timeline:

  var slider_relieved = {
    type: 'wof-slider-response',
    labels: ['not at all relieved', 'very relieved'],
    clear_screen: false,
    post_trial_gap: 1000
  }
  

  var test_procedure = {
    timeline: [trial, slider_happy, slider_sad, slider_relieved],
    timeline_variables: trial_list,
    randomize_order: true,
    sample: {
        type: 'without-replacement',
        size: 5, // sample 5 trials, without replacement
    }
  }
  timeline.push(test_procedure);

However, this doesn't show when I test it in Chrome. Do I need to specify it elsewhere, too?

**Comment by LeilaIliffeHodgetts** [comment]
Ok, I feel like this may become a diary of my workings out. 

I need to 'save' any edits before they are reflected in the .html test. 

I've now managed to change the instructions and add the 'relieved' slider in. I will now try to add the other two sliders in.

**Comment by LilyFG** [comment]
Nice work! Using this as a diary is fine because it means you will have a record of the issues and be able to find the solutions again later. Yes, the file needs to be saved because Chrome will read the last saved version, not an in progress version. It's amazing how many times I've forgotten to do that and felt frustrated!

**Comment by LeilaIliffeHodgetts** [comment]
Great! Thanks.

How do I put the index.html and WOF.html (with the instructions) together? So that it runs as a complete experiment. Will also need an end page!

**Comment by LilyFG** [comment]
Ah so there are two ways to do this:

1. You can keep them separate, and redirect from one to the other using the on_finish function in the jsPsyc.init part of the WOF.html file
```
jsPsych.init({
  timeline: [...],
  on_finish: function(){
    window.location = "index.html" // the location to redirect to is the index file in the same directory
  }
});
```
2. You can copy the instructions procedure from the WOF file into the index file and add the instructions to the timeline in the index file (this is probably the better option). You may need to add the instruction plugin to the list of plugins at the top of the file if it's not already there.

**Comment by LeilaIliffeHodgetts** [comment]
Great! Thank you. 

I've added the 'welcome_block' and 'instructions' to the timeline in the index.html and these now show. How should I add in two practice trials?

**Comment by LilyFG** [comment]
Sorry, I've not made this bit easy for you! Have a think about what you want the variable values to be. Take a look at the "trial_list.js" file (in a text editor). Each object wrapped in curly brackets is a trial. 

I would make a copy of this file but just include the two trials that you want for the practice. Name it something like prac_list.js. You also need to change the name of the variable inside the file, so it should say ```var prac_list = {...}``` 

Then you need to read that file into the index.html file at the top using ```<script ...>``` as with the trial_list.js file. Then the last thing you need to do is to create a new procedure (you could call it ```prac_procedure``` in the index file that is the same as the ```test_procedure``` but calls the ```prac_list``` instead of the ```trial_list```. 

Good luck, let me know if you get stuck!
